CREATE DATABASE burgers_db;

USE DATABASE burgers_db;

CREATE TABLE burgers 
(
	id INT NOT NULL AUTO_INCREMENT,
	burger_name varchar(150) NOT NULL,
	devoured BOOLEAN DEFAULT FALSE NOT NULL,
	date TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);

